server:
  port: 8081
security:
  oauth2:
    client:
      clientId: 9a244e57
      clientSecret: 12ea7b9b23fe2e7f39741ba2e352addc
    resource:
      user-info-uri: http://192.168.1.138:8080/auth/realms/3scalesso/protocol/openid-connect/userinfo
      token-info-uri: http://192.168.1.138:8080/auth/realms/3scalesso/protocol/openid-connect/token/introspect