server:
  port: 8082

security:
  oauth2:
    resource:
      id: account
    client:
      client-id: spring-oidc-clientid
      client-secret: 36ffc90a-7a4f-4b1a-9578-c8463a3c4ecf
      grant-type: client_credentials
      scope: openid
      access-token-uri: http://localhost:8080/auth/realms/oidcrealm/protocol/openid-connect/token
omar:
  server:
    endpoint-url: http://omarserver:8081/me