server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        #GUI
        registration:
          keycloak:
            provider: keycloak
            client-id: spring-oidc-clientid-for-api
            client-secret: 0fde0459-546b-4440-8aca-0b0843a3543f
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          #GUI
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/oidcrealm
omar:
  server:
    endpoint-url: http://localhost:8081/me
