server:
  port: 8082

security:
  oauth2:
    client:
      client-id: spring-oidc-clientid-for-api
      client-secret: 0fde0459-546b-4440-8aca-0b0843a3543f
      grant-type: client_credentials
      access-token-uri: http://localhost:8080/auth/realms/oidcrealm/protocol/openid-connect/token
omar:
  server:
    endpoint-url: http://omarserver:8081/me