server:
  port: 8082

security:
  oauth2:
    client:
      clientId: b01ad011
      clientSecret: a8ac56b85ea919b4c10f109a80d97939
      grant-type: client_credentials
      access-token-uri: http://192.168.1.138:8080/auth/realms/3scalesso/protocol/openid-connect/token
omar:
  server:
    endpoint-url: https://omarapi-3scale-apicast-staging.192.168.99.100.nip.io:443/hello